package io.batchadmin.domain;

import javax.sql.DataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Creates the two tables backing the admin component (dynamic job definitions and schedules) if
 * they do not exist yet. Column types are adapted to the detected database so the component stays
 * non-intrusive and works on H2 and PostgreSQL out of the box.
 */
public class BatchAdminSchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(BatchAdminSchemaInitializer.class);

    private final JdbcTemplate jdbcTemplate;

    public BatchAdminSchemaInitializer(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }

    public void initialize() {
        String product = detectProduct();
        boolean postgres = product.contains("postgres");
        // TEXT on PostgreSQL, CLOB elsewhere (H2/Oracle); identity syntax is shared SQL standard.
        String textType = postgres ? "TEXT" : "CLOB";
        String identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_DEFINITION (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL UNIQUE,
                    DESCRIPTION VARCHAR(1000),
                    STEPS_JSON %s NOT NULL,
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity, textType));

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_SCHEDULE (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL,
                    CRON_EXPRESSION VARCHAR(100) NOT NULL,
                    PARAMETERS_JSON %s,
                    ENABLED BOOLEAN NOT NULL,
                    DESCRIPTION VARCHAR(1000),
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity, textType));

        log.info("[batch-admin] Schema ready (database: {})", product.isBlank() ? "unknown" : product);
    }

    private String detectProduct() {
        try {
            String name = jdbcTemplate.execute(
                    (org.springframework.jdbc.core.ConnectionCallback<String>) connection ->
                            connection.getMetaData().getDatabaseProductName());
            return name == null ? "" : name.toLowerCase();
        } catch (RuntimeException ex) {
            log.warn("[batch-admin] Could not detect database product: {}", ex.getMessage());
            return "";
        }
    }
}
