package io.batchadmin.domain;

import javax.sql.DataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Creates the two tables backing the admin component (dynamic job definitions and schedules) if
 * they do not exist yet. Column types are adapted to the detected database so the component stays
 * non-intrusive and works on H2 and PostgreSQL out of the box.
 */
public class BatchAdminSchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(BatchAdminSchemaInitializer.class);

    private final JdbcTemplate jdbcTemplate;

    public BatchAdminSchemaInitializer(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }

    public void initialize() {
        String product = detectProduct();
        boolean postgres = product.contains("postgres");
        // TEXT on PostgreSQL, CLOB elsewhere (H2/Oracle); identity syntax is shared SQL standard.
        String textType = postgres ? "TEXT" : "CLOB";
        String identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_DEFINITION (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL UNIQUE,
                    DESCRIPTION VARCHAR(1000),
                    STEPS_JSON %s NOT NULL,
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity, textType));

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_DEFINITION_VERSION (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL,
                    VERSION_NUMBER INTEGER NOT NULL,
                    DESCRIPTION VARCHAR(1000),
                    STEPS_JSON %s NOT NULL,
                    AUTHOR VARCHAR(200),
                    CHANGE_TYPE VARCHAR(20),
                    CHANGE_NOTE VARCHAR(1000),
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity, textType));

        // Audit columns were added after the table shipped: add them to pre-existing tables.
        // ADD COLUMN IF NOT EXISTS is supported by both H2 and PostgreSQL and is a no-op when the
        // table was just created above.
        addColumnIfMissing("BATCH_ADMIN_JOB_DEFINITION_VERSION", "AUTHOR", "VARCHAR(200)");
        addColumnIfMissing("BATCH_ADMIN_JOB_DEFINITION_VERSION", "CHANGE_TYPE", "VARCHAR(20)");
        addColumnIfMissing("BATCH_ADMIN_JOB_DEFINITION_VERSION", "CHANGE_NOTE", "VARCHAR(1000)");

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_SCHEDULE (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL,
                    CRON_EXPRESSION VARCHAR(100) NOT NULL,
                    PARAMETERS_JSON %s,
                    ENABLED BOOLEAN NOT NULL,
                    DESCRIPTION VARCHAR(1000),
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity, textType));

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_JOB_TRIGGER (
                    ID %s PRIMARY KEY,
                    SOURCE_JOB VARCHAR(200) NOT NULL,
                    TARGET_JOB VARCHAR(200) NOT NULL,
                    CONDITION_TYPE VARCHAR(20) NOT NULL,
                    ENABLED BOOLEAN NOT NULL,
                    INHERIT_PARAMS BOOLEAN DEFAULT FALSE NOT NULL,
                    PARAMETERS_JSON VARCHAR(2000),
                    DESCRIPTION VARCHAR(1000),
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity));

        // Parameter-passing columns were added after the trigger table shipped: add them to
        // pre-existing tables (no-op when the table was just created above).
        addColumnIfMissing("BATCH_ADMIN_JOB_TRIGGER", "INHERIT_PARAMS", "BOOLEAN DEFAULT FALSE NOT NULL");
        addColumnIfMissing("BATCH_ADMIN_JOB_TRIGGER", "PARAMETERS_JSON", "VARCHAR(2000)");

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_SCHEDULE_LOCK (
                    SCHEDULE_ID BIGINT NOT NULL,
                    FIRE_SECOND BIGINT NOT NULL,
                    INSTANCE_ID VARCHAR(200),
                    CLAIMED_AT TIMESTAMP NOT NULL,
                    PRIMARY KEY (SCHEDULE_ID, FIRE_SECOND)
                )""");

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS BATCH_ADMIN_ALERT_RULE (
                    ID %s PRIMARY KEY,
                    JOB_NAME VARCHAR(200) NOT NULL,
                    RULE_TYPE VARCHAR(20) NOT NULL,
                    THRESHOLD_MILLIS BIGINT,
                    CHANNEL VARCHAR(20) NOT NULL,
                    TARGET VARCHAR(1000),
                    ENABLED BOOLEAN NOT NULL,
                    DESCRIPTION VARCHAR(1000),
                    CREATED_AT TIMESTAMP NOT NULL
                )""".formatted(identity));

        log.info("[batch-admin] Schema ready (database: {})", product.isBlank() ? "unknown" : product);
    }

    /** Idempotently adds a column to an existing table (no-op when it is already present). */
    private void addColumnIfMissing(String table, String column, String type) {
        try {
            jdbcTemplate.execute(
                    "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + column + " " + type);
        } catch (RuntimeException ex) {
            log.warn("[batch-admin] Could not ensure column {}.{}: {}", table, column, ex.getMessage());
        }
    }

    private String detectProduct() {
        try {
            String name = jdbcTemplate.execute(
                    (org.springframework.jdbc.core.ConnectionCallback<String>) connection ->
                            connection.getMetaData().getDatabaseProductName());
            return name == null ? "" : name.toLowerCase();
        } catch (RuntimeException ex) {
            log.warn("[batch-admin] Could not detect database product: {}", ex.getMessage());
            return "";
        }
    }
}
